CREATE TABLE DOCTORS (
    D_ID INTEGER PRIMARY KEY,
    D_NAME TEXT NOT NULL,
    D_GENDER TEXT,
    D_AGE INTEGER,
    D_SPECIALIZATION TEXT,
    D_YEARS_OF_EXPERIENCE INTEGER,
    D_CONTACT TEXT,
    D_STREET TEXT,
    D_CITY TEXT
);


CREATE TABLE PATIENTS (
    P_ID INTEGER PRIMARY KEY,
    P_NAME TEXT NOT NULL,
    P_GENDER TEXT,
    P_AGE INTEGER,
    P_DISEASE TEXT,
    P_CONTACT TEXT,
    P_STREET TEXT,
    P_CITY TEXT
);

CREATE TABLE NURSES (
    N_ID INTEGER PRIMARY KEY,
    N_NAME TEXT NOT NULL,
    N_SPECIALIZATION TEXT,
    N_SHIFT INTEGER,
    N_STREET TEXT,
    N_CITY TEXT
);

CREATE TABLE P_ASSIGNMENT (
    P_ID INTEGER,
    D_ID INTEGER,
    PRIMARY KEY (P_ID, D_ID),
    FOREIGN KEY (P_ID) REFERENCES PATIENTS(P_ID),
    FOREIGN KEY (D_ID) REFERENCES DOCTORS(D_ID)
);

CREATE TABLE N_ASSIST (
    N_ID INTEGER,
    D_ID INTEGER,
    PRIMARY KEY (N_ID, D_ID),
    FOREIGN KEY (N_ID) REFERENCES NURSES(N_ID),
    FOREIGN KEY (D_ID) REFERENCES DOCTORS(D_ID)
);

CREATE TABLE TESTS (
    T_ID INTEGER PRIMARY KEY,
    T_NAME TEXT NOT NULL,
    P_ID INTEGER,
    D_ID INTEGER,
    I_ID INTEGER,
    T_DATE TEXT,
    T_RESULT TEXT,
    FOREIGN KEY (P_ID) REFERENCES PATIENTS(P_ID),
    FOREIGN KEY (D_ID) REFERENCES DOCTORS(D_ID),
    FOREIGN KEY (I_ID) REFERENCES INSTRUMENTS(I_ID)
);


CREATE TABLE INSTRUMENTS (
    I_ID INTEGER PRIMARY KEY,
    I_NAME TEXT NOT NULL,
    I_MANUFACTURER TEXT
);
