SELECT DOCTORS.D_NAME
FROM DOCTORS
JOIN P_ASSIGNMENT ON DOCTORS.D_ID = P_ASSIGNMENT.D_ID
JOIN PATIENTS ON P_ASSIGNMENT.P_ID = PATIENTS.P_ID
WHERE PATIENTS.P_NAME = 'RICHARD MILLER';

SELECT TESTS.*
FROM TESTS
JOIN PATIENTS ON TESTS.P_ID = PATIENTS.P_ID
WHERE PATIENTS.P_DISEASE LIKE '%cancer%';

SELECT *
FROM INSTRUMENTS
WHERE I_MANUFACTURER LIKE 'S%';

SELECT *, MAX(D_YEARS_OF_EXPERIENCE) AS MostExperience
FROM DOCTORS;

SELECT PATIENTS.P_NAME
FROM PATIENTS
JOIN P_ASSIGNMENT ON PATIENTS.P_ID = P_ASSIGNMENT.P_ID
JOIN DOCTORS ON P_ASSIGNMENT.D_ID = DOCTORS.D_ID
WHERE DOCTORS.D_NAME = 'JAMES SMITH'
AND PATIENTS.P_STREET = DOCTORS.D_STREET
AND PATIENTS.P_CITY = DOCTORS.D_CITY;

SELECT NURSES.N_NAME, COUNT(N_ASSIST.D_ID) AS NumberOfDoctors
FROM NURSES
JOIN N_ASSIST ON NURSES.N_ID = N_ASSIST.N_ID
GROUP BY NURSES.N_NAME
HAVING COUNT(N_ASSIST.D_ID) >= 2;

SELECT DOCTORS.D_NAME, COUNT(N_ASSIST.N_ID) AS NumberOfNurses
FROM DOCTORS
LEFT JOIN N_ASSIST ON DOCTORS.D_ID = N_ASSIST.D_ID
GROUP BY DOCTORS.D_NAME
ORDER BY NumberOfNurses DESC;

SELECT NURSES.N_NAME
FROM NURSES
LEFT JOIN N_ASSIST ON NURSES.N_ID = N_ASSIST.N_ID
WHERE N_ASSIST.D_ID IS NULL;

UPDATE DOCTORS
SET D_YEARS_OF_EXPERIENCE = D_YEARS_OF_EXPERIENCE + 5
WHERE D_GENDER = 'Female';

DELETE FROM TESTS
WHERE T_RESULT = 'negative';
